name = "sonicjs-ai"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# Statický assets
[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"
# Cloudflare Images configuration (optional)
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media.yourdomain.com"

[[d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "a098ea4b-9eef-4041-a9a7-349a1e8b3331"

# R2 Bucket for media storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-dev"

[env.preview]
name = "sonicjs-ai-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
# IMAGES_ACCOUNT_ID = "your-account-id"
# CDN_DOMAIN = "media-preview.yourdomain.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "sonicjs-dev"
database_id = "a098ea4b-9eef-4041-a9a7-349a1e8b3331"

[[env.preview.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-preview"

[env.production]
name = "sonicjs-ai-prod"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sonicjs-prod"
database_id = "e12b26eb-5a2e-4a80-8da2-90d50ab8073f"

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-prod"