name = "sonicjs"
main = "src/index.ts"
compatibility_date = "2025-06-06"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

# Statický assets
[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
# Cloudflare Images configuration (optional)
# IMAGES_ACCOUNT_ID = "your-id"
# CDN_DOMAIN = "media.yourdomain.com"

[[d1_databases]]
binding = "DB"
database_name = "sonicjs-prod"
database_id = "e89894e1-00a2-44cd-97ea-bf8c5dafe2a0"

# R2 Bucket for media storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-media-prod"