name: E2E Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Setup Cloudflare D1 Database
      run: |
        # Create test database
        npx wrangler d1 create sonicjs-test --local
        
        # Run migrations
        npm run db:migrate
    
    - name: Start development server
      run: |
        npm run dev &
        
        # Wait for server to be ready
        timeout 60 bash -c 'until curl -f http://localhost:8787/health; do sleep 2; done'
      env:
        NODE_ENV: test
    
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        CI: true
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-screenshots
        path: test-results/
        retention-days: 7

  e2e-tests-mobile:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Setup Cloudflare D1 Database
      run: |
        npx wrangler d1 create sonicjs-test --local
        npm run db:migrate
    
    - name: Start development server
      run: |
        npm run dev &
        timeout 60 bash -c 'until curl -f http://localhost:8787/health; do sleep 2; done'
      env:
        NODE_ENV: test
    
    - name: Run Mobile E2E tests
      run: npx playwright test --project="Mobile Chrome" --project="Mobile Safari"
      env:
        CI: true
    
    - name: Upload Mobile Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mobile-playwright-report
        path: playwright-report/
        retention-days: 30 